### ISSUE TITLE
Runoff em Python

### ISSUE THREAD

**Issue by OsmarCLFilho** [emap-ic/syllabus#19]
Como comentado em aula, deve ser feita uma versão em Python do código runoff do assignment 3, aceitando arquivos como entrada.

Aguardo permissão para criação de uma nova branch para o desenvolvimento desse código.

**Comment by arademaker** [comment]
Perfeito, pode criar um branch `issue-19`, completar o código em https://github.com/emap-ic/syllabus/blob/main/week-06/src/runoff/runoff.py e fazer o PR...

**Comment by arademaker** [comment]
Ist foi feito?

**Comment by OsmarCLFilho** [comment]
Há algum tempo, o código já foi _mergido_ na pasta da semana 6. Devo apagar esse issue agora?
