### ISSUE TITLE
comentários lab week 03

### ISSUE THREAD

**Issue by arademaker** [emap-ic/syllabus#4]
Meu querido professor, olha como ficou minha função:

```c
void bubble(int *numbers, int size)
{
  for(int j = 0; j < size; j++)
  {
    for(int i = 0; i < size - 1; i++)
    {
      if(numbers[i] > numbers[i+1])
      {
        int aux = numbers[i];
        numbers[i] = numbers[i+1];
        numbers[i+1] = aux;
      }
    }
  }
}
```

**Comment by OsmarCLFilho** [comment]
Estimado professor Rademaker. Segue minhas funções dos sorts selection e bubble:
```c
void selection(int *numbers, int size)
{
  for(int j = 0; j < size-1; j++)
  {
    int smallPos = j;
  
    for(int i = j+1; i < size; i++)
    {
      if(numbers[i] < numbers[smallPos])
      {
        smallPos = i;
      }
    }

    int tmp = numbers[j];
    numbers[j] = numbers[smallPos];
    numbers[smallPos] = tmp;
  }
}

void bubble(int *numbers, int size)
{
  bool changed;

  do
  {
    changed = false;

    for(int i = 0; i < size-1; i++)
    {
      if(numbers[i] > numbers[i+1])
      {
        int tmp = numbers[i+1];
        numbers[i+1] = numbers[i];
        numbers[i] = tmp;

        changed = true;
      }
    }
  }
  while(changed);
}
```

**Comment by arademaker** [comment]
Excelente @OsmarCLFilho, sua versão corresponde a minha agora no repo https://github.com/emap-ic/syllabus/blob/main/week-03/lab/sort.c

**Comment by arademaker** [comment]
O merge sort foi implementado em https://github.com/emap-ic/syllabus/blob/main/week-03/lab/sort.c#L55-L101 e os demais ajustes na main para que ele possa ser usado também. Em https://github.com/emap-ic/syllabus/blob/main/week-03/lab/sort.c#L115 e https://github.com/emap-ic/syllabus/blob/main/week-03/lab/sort.c#L162-L172. 

Note que este merge sort é recursivo, o corpo da função chama ela mesma, e como as demais funções passa o array `numbers`  [por referência](9https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_reference) e não [por valor](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_value). Mas a complexidade vem do fato de não serem usadas regiões extra de memória, o array é modificado 'in place', sem alocação de memória extra.   O preço desta otimização, uso bastante econômico da memória, é um código mais elaborado e, possivelmente, mais complexo (mais passos de execução).
