### ISSUE TITLE
comentários lab week 02

### ISSUE THREAD

**Issue by tayaracausanilhas** [emap-ic/syllabus#9]

**Comment by tayaracausanilhas** [comment]
Professor, segue a minha alternativa ao lab:

```
  #include <ctype.h>
  #include <cs50.h>
  #include <stdio.h>
  #include <string.h>
  
  // Points assigned to each letter of the alphabet
  int POINTS[] = {1, 3, 3, 2, 1, 4, 2, 4, 1, 8, 5, 1, 3, 1, 1, 3, 10, 1, 1, 1, 1, 4, 4, 8, 4, 10};
  
  int compute_score(string word);
  
  int main(void)
  {
   
   // Get input words from both players
    string word1 = get_string("Player 1: ");
    string word2 = get_string("Player 2: ");
  
    // Score both words
    int score1 = compute_score(word1);
    int score2 = compute_score(word2);
  
    // Print the winner 
    if (score1 > score2)
      printf("Player 1 wins!"); 
    else if (score1 == score2) 
      printf("Tie!");
    else
      printf("Player 2 wins!");
  }
  
  int compute_score(string word)
  {
    
   // Compute and return score for string
   int sum = 0;
   int numb;
   int n = strlen(word);
     
   for(int i=0; i<n; i++){ 
      if(isupper(word[i])){
        numb = word[i]-65;
        numb = POINTS[numb];
     
    }
      if(islower(word[i])){
        numb = word[i]-97;
        numb = POINTS[numb];
      }
      else{
        numb = 0;
      }
     sum += numb;
    }
    return sum;
  }
```

**Comment by arademaker** [comment]
comparado com a solução atual da @JuCarv-bit :

O código da @JuCarv-bit é um pouco menos claro, o score é computado em um único `if` onde a posição no array points é computada de uma única vez para os char minúsculos e maiúsculos. Isto porque, ela usou uma regularidade da estrutura da tabela [ASCII](https://www.asciichart.com), obviamente não é uma coincidência a tabela ASCII ter esta regularidade.

```c
...
      if((64 < c && c < 91 ) || (96 < c && c < 123))
      {
        score += POINTS[c % 32 - 1];
      }
...
```
Mas eu tendo a preferir códigos mais claros do que códigos mais 'espertos' que requerem do leitor mais tempo para revisão.  Obviamente, se o código mais 'esperto' constitui uma forma mais eficiente de resolver o problema, então o preço se paga. Mas aqui não acho que seja o caso. As funções `isupper` e `islower` tem complexidade provavelmente O(1).

Por outro lado, vc define a variável `n` fora do `for`, o que não está errado mas também não é o ideal. Ela só precisa existir durante o loop. Seu segundo `if` não deve nunca ser executado se o primeiro `if` for executado, logo deveria ser um `else if`. A expressão final a ser somada ao `sum` é tão simples que não justifica usar uma variável intermediária como `numb` e ao abolir esta variável intermediaria também evito fazer soma de zeros.

Sua indentação ficou confusa quando copiou/colou aqui no Github talvez... e esqueceu de dizer que seu bloco é de código C -- vide [aqui](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

Faz sentido? Vejam 35c2c7d

**Comment by arademaker** [comment]
Um pequeno ajuste final.. se em https://github.com/emap-ic/syllabus/blob/main/week-02/lab/scrabble.c#L39 a variável `c` é declarada, aqui tudo bem, apenas torna o acesso a o char mais simples, todas as linhas abaixo podem usar esta variável não é? Não faz sentido continuar recorrendo a `word[i]` depois de ter declarado c e atribuído esta expressão à `c`.
